version: "3"
services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./docker/rust
        container_name: coombes-rust
        tty: true
        ports:
            - 8080:8080
        volumes:
            - ./backend:/var/www/app
    next:
        build:
            dockerfile: Dockerfile
            context: ./docker/next
        container_name: coombes-next
        tty: true
        ports:
            - 3000:3000
        volumes:
        - ./frontend:/var/www/next
        environment:
        - WATCHPACK_POLLING=true
    db:
        image: mysql:8.0
        container_name: coombes_db
        cap_add:
        - SYS_NICE
        volumes:
        - ./data/db-store:/var/lib/mysql
        - ./data/logs/db:/var/log/mysql
        - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - TZ=${TZ}
        ports:
        - 3306:${DB_PORT}
