version: "3"
services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./docker/rust
        container_name: coombes-rust
        tty: true
        ports:
            - 8080:8080
        volumes:
            - ./backend:/var/www/app

