version: "3"
services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./docker/rust
        container_name: coombes-rust
        tty: true
        ports:
            - 8080:8080
        volumes:
            - ./backend:/var/www/app
    next:
        build:
            dockerfile: Dockerfile
            context: ./docker/next
        container_name: coombes-next
        tty: true
        ports:
            - 3000:3000
        volumes:
        - ./frontend:/var/www/next
        environment:
        - WATCHPACK_POLLING=true

