name: develop-ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: copy .env
        run: |
          cp ./.env.example ./.env
          cp ./backend/.env.local ./backend/.env

